name: Update Open Issues

# 触发条件：新 issue 被创建时
on:
  issues:
    types: [opened]

jobs:
  update-issue-report:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Call GitHub API to get open issues
      - name: Fetch open issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 设置 GitHub Token
        run: |
          # 调用 GitHub API 获取未关闭的 issues，并写入 open_issues.md
          echo "# Open Issues" > open_issues.md
          curl -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues?state=open \
            | jq -r '.[] | "## Issue #\(.number)\n**Title**: \(.title)\n**Author**: \(.user.login)\n**Content**: \(.body)\n\n"' >> open_issues.md

      # Step 3: Commit the markdown file
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add open_issues.md
          git commit -m "Update open issues report"
          git push
